version: "3.8"

networks:
  default:
    name: ergo-node

volumes:
  ergo_node:
    external: true
  ergo_redis:
    external: true

services:
  # Ergo blockchain node
  node:
    image: ergoplatform/ergo:v4.0.41
    container_name: ergo-node
    command: --mainnet -c /etc/ergo.conf
    volumes:
      - ergo_node:/home/ergo/.ergo
      - ./ergo.conf:/etc/ergo.conf:ro
    ports:
      - "9053:9053"
      - "9030:9030"
    restart: unless-stopped
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  # Postgresql database
  db:
    build:
      context: ./db
      args:
        EXPLORER_VERSION: 9.16.4
    # -- Ucomment and edit if wanting to set custom work_mem value
    # -- https://www.postgresql.org/docs/current/runtime-config-resource.html
    # command: ["postgres", "-c", "work_mem=4MB"]
    environment:
      POSTGRES_DB: ergo
      POSTGRES_USER: ergo
      # POSTGRES_PASSWORD: "postgres"
    env_file:
      # Defines POSTGRES_PASSWORD
      - ./db/db.secret
    volumes:
      # Mapped volume for easier Postgres upgrades.
      # Make sure the path exists or edit it here.
      # See also readme_pg_upgrade.md
      - /var/lib/explorer_pg/14/data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: unless-stopped
    logging:
      options:
        max-size: "10m"
        max-file: "3"
        
  # Redis
  redis:
    image: redis:latest
    restart: unless-stopped
    command: ["redis-server"]
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - ergo_redis:/usr/local/etc/redis

  # GraphQL
  graphql:
    build:
      context: ./graphql
      args:
        VERSION: "0.1.0"
    environment:
      # database host address    
      DB_HOST: db                     
      # database host port      
      DB_PORT: 5432                   
      # database name      
      DB_NAME: ergo                   
      # database user name      
      DB_USER_NAME: ergo          
      # database password      
      # DB_USER_PWD: "graphql"            
      # ergo node address and port
      ERGO_NODE_ADDRESS: node:9053    
      # optional: MAINNET or TESTNET      
      NETWORK: MAINNET                
      # optional: redis host address
      REDIS_HOST: redis               
      # optional: redis host port      
      REDIS_PORT: 6379                
      # optional: redis username      
      REDIS_USER_NAME: default               
      # optional: redis user password      
      REDIS_USER_PWD: redispassword
      # optional: maximum query depth
      MAX_QUERY_DEPTH: 5              
    env_file:
      # Defines DB_USER_PWD
      - ./db/db.secret
    links:
      - "db"
      - "redis"
    ports:
      - 3001:3000
      